first commit Ansible + terraform and CD

diff --git a/.github/workflows/cd.yaml b/.github/workflows/cd.yaml
--- a/.github/workflows/cd.yaml
+++ b/.github/workflows/cd.yaml
@@ -64,19 +64,57 @@ jobs:
       - name: Terraform Init
         working-directory: infra/terraform
         run: terraform init -input=false
-      
+
       # 6. Terraform Plan
       - name: Terraform plan
         working-directory: infra/terraform
-        run: terraform plan -input=false -out=tfplan
+        run: terraform plan -input=false -out=tfplan -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
 
       # 7. Terraform Apply
-      #- name: Terraform apply
-      #  working-directory: infra/terraform
-      #  run: terraform apply -input=fase -auto-approve tfplan
+      - name: Terraform apply
+        working-directory: infra/terraform
+        run: terraform apply -input=false -auto-approve -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" tfplan
 
       # 8. Install Ansible and Plugins
       - name: Install Ansible + plugins
         run: |
           sudo apt-get update
           sudo apt-get install -y ansible python3-boto3 python3-botocore
+
+      # 9. Generate Ansible Inventory
+      - name: Generate inventory.ini
+        working-directory: infra/ansible
+        run: |
+          PUBLIC_IP=$(terraform -chdir=../terraform output -raw ec2_public_ip)
+          echo "[voting_app]" > inventory.ini
+          echo "$PUBLIC_IP ansible_user=ubuntu" >> inventory.ini
+
+      # 10. Run Ansible Playbook
+      - name: Run Ansible
+        working-directory: infra/ansible
+        env:
+          ANSIBLE_HOST_KEY_CHECKING: "False"
+        run: |
+          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > key.pem
+          chmod 600 key.pem
+          ansible-playbook -i inventory.ini playbook.yml \
+            --private-key key.pem \
+            -e "ghcr_username=${{ github.actor }} \
+                ghcr_token=${{ secrets.GITHUB_TOKEN }} \
+                repo_slug=${GITHUB_REPOSITORY,,}"
+
+      # 10. Smoke Test
+      - name: Run Smoke Test
+        run: |
+          APP_URL=$(terraform -chdir=infra/terraform output -raw app_url)
+          echo "Testing app at $APP_URL"
+          for i in {1..10}; do
+            if curl -fs "$APP_URL/healthz"; then
+              echo "App is healthy!"
+              exit 0
+            fi
+            echo "Waiting for app..."
+            sleep 5
+          done
+          echo "App failed health check"
+          exit 1
